export const container: string;
export const body: string;
export const image: string;
export const info: string;
export const name: string;
export const types: string;
export const footer: string;
export const captured: string;
export const captureBtn: string;
